[general]
live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutCirc"
color = "#a9b1d6"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[window]
opacity = 0.9
dimensions = { columns = 80, lines = 30 }
# decorations = "None"
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[scrolling]
history = 500
multiplier = 1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[font]
size = 12
builtin_box_drawing = true

# [font.normal]
# family = "JetBrains Mono"
# style = "Regular"

[window.padding]
x = 5
y = 5

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

